/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

/**
 *
 * @author Mate
 */
public class StatisticForm extends javax.swing.JDialog {

    /**
     * Creates new form StatisticForm
     */
    public StatisticForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public void setStaticstics(int allQuestion, int allCorrect,int allWrong, double allRatio, 
            int wordQuestion, int wordCorrect, int wordWrong, double wordRatio, 
            int sessionQuestion, int sessionCorrect, int sessionWrong, double sessionRatio, String word){
        lbAllQuestion.setText(allQuestion+"");
        lbAllCorrect.setText(allCorrect+"");
        lbAllWrong.setText(allWrong+"");
        lbAllRatio.setText(allRatio+" %");
        
        lbWordQuestion.setText(wordQuestion+"");
        lbWordCorrect.setText(wordCorrect+"");
        lbWordWrong.setText(wordWrong+"");
        lbWordRatio.setText(wordRatio+" %");
        
        lbSessionQuestion.setText(sessionQuestion+"");
        lbSessionCorrect.setText(sessionCorrect+"");
        lbSessionWrong.setText(sessionWrong+"");
        lbSessionRatio.setText(sessionRatio+" %");
        
        lbHunWord.setText(word);
        tpnStat.setSelectedIndex(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btOk = new javax.swing.JButton();
        tpnStat = new javax.swing.JTabbedPane();
        pnAllStat = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbAllQuestion = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lbAllCorrect = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbAllWrong = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lbAllRatio = new javax.swing.JLabel();
        pnWordStat = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbHunWord = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbWordQuestion = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbWordCorrect = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbWordWrong = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbWordRatio = new javax.swing.JLabel();
        pnSessionStat = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbSessionQuestion = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbSessionCorrect = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbSessionWrong = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbSessionRatio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Statisztika");
        setPreferredSize(new java.awt.Dimension(550, 300));

        btOk.setText("OK");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });
        jPanel1.add(btOk);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pnAllStat.setLayout(new java.awt.GridLayout(5, 2, 5, 5));

        jLabel6.setText("A regisztráció óta");
        pnAllStat.add(jLabel6);
        pnAllStat.add(jLabel8);

        jLabel12.setText("Megjelent szavak száma:");
        pnAllStat.add(jLabel12);

        lbAllQuestion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204)));
        pnAllStat.add(lbAllQuestion);

        jLabel15.setText("Helyes válaszok száma:");
        pnAllStat.add(jLabel15);

        lbAllCorrect.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204)));
        pnAllStat.add(lbAllCorrect);

        jLabel18.setText("Rossz válaszok száma:");
        pnAllStat.add(jLabel18);

        lbAllWrong.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204)));
        pnAllStat.add(lbAllWrong);

        jLabel20.setText("Százalék:");
        pnAllStat.add(jLabel20);

        lbAllRatio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204)));
        pnAllStat.add(lbAllRatio);

        tpnStat.addTab("Összesített statisztika", pnAllStat);

        pnWordStat.setLayout(new java.awt.GridLayout(5, 2, 5, 5));

        jLabel1.setText("Az alábbi szó statisztikája:");
        pnWordStat.add(jLabel1);

        lbHunWord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        pnWordStat.add(lbHunWord);

        jLabel5.setText("Eddigi megjelenések száma:");
        pnWordStat.add(jLabel5);

        lbWordQuestion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        pnWordStat.add(lbWordQuestion);

        jLabel4.setText("Helyes válaszok száma:");
        pnWordStat.add(jLabel4);

        lbWordCorrect.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        pnWordStat.add(lbWordCorrect);

        jLabel7.setText("Rossz válaszok száma:");
        pnWordStat.add(jLabel7);

        lbWordWrong.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        pnWordStat.add(lbWordWrong);

        jLabel9.setText("Százalék:");
        pnWordStat.add(jLabel9);

        lbWordRatio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        pnWordStat.add(lbWordRatio);

        tpnStat.addTab("Aktuális szó statisztika", pnWordStat);

        pnSessionStat.setLayout(new java.awt.GridLayout(5, 2, 5, 5));

        jLabel2.setText("A bejelentkezés óta");
        pnSessionStat.add(jLabel2);
        pnSessionStat.add(jLabel3);

        jLabel10.setText("Megjelent szavak száma:");
        pnSessionStat.add(jLabel10);

        lbSessionQuestion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204)));
        pnSessionStat.add(lbSessionQuestion);

        jLabel11.setText("Helyes válaszok száma:");
        pnSessionStat.add(jLabel11);

        lbSessionCorrect.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204)));
        pnSessionStat.add(lbSessionCorrect);

        jLabel13.setText("Rossz válaszok száma:");
        pnSessionStat.add(jLabel13);

        lbSessionWrong.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204)));
        pnSessionStat.add(lbSessionWrong);

        jLabel14.setText("Százalék:");
        pnSessionStat.add(jLabel14);

        lbSessionRatio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204)));
        pnSessionStat.add(lbSessionRatio);

        tpnStat.addTab("Aktuális munkameneti statisztika", pnSessionStat);

        getContentPane().add(tpnStat, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        dispose();
    }//GEN-LAST:event_btOkActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbAllCorrect;
    private javax.swing.JLabel lbAllQuestion;
    private javax.swing.JLabel lbAllRatio;
    private javax.swing.JLabel lbAllWrong;
    private javax.swing.JLabel lbHunWord;
    private javax.swing.JLabel lbSessionCorrect;
    private javax.swing.JLabel lbSessionQuestion;
    private javax.swing.JLabel lbSessionRatio;
    private javax.swing.JLabel lbSessionWrong;
    private javax.swing.JLabel lbWordCorrect;
    private javax.swing.JLabel lbWordQuestion;
    private javax.swing.JLabel lbWordRatio;
    private javax.swing.JLabel lbWordWrong;
    private javax.swing.JPanel pnAllStat;
    private javax.swing.JPanel pnSessionStat;
    private javax.swing.JPanel pnWordStat;
    private javax.swing.JTabbedPane tpnStat;
    // End of variables declaration//GEN-END:variables
}
